apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: demo-service
spec:
  host: demo-service
  subsets:
  - name: v10
    labels:
      version: v10
  - name: v11
    labels:
      version: v11
