trigger:
- master

variables:
- group: variable-group-commit
- name: imageName
  value: 'windows-2019'
- name: buildConfiguration
  value: 'Release'
- name: projects
  value: '**/msp-test-fn.csproj'
- name: testProjects
  value: '**/msp-test-fn.Tests.csproj'
- name: dotnetSdkVersion
  value: '2.1.x'
- name: azureSubscription
  value: 'AzureSponsorships'
- name: functionAppsType
  value: 'functionApp'
- name: environment
  value: 'Commit-Stage'

stages:
- stage: Build
  jobs:
  - template: pipelines/build-pipelines.yml
    parameters:
      imageName: $(imageName)
      buildConfiguration: $(buildConfiguration)
      projects: $(projects)
      testProjects: $(testProjects)
      dotnetSdkVersion: $(dotnetSdkVersion)
    
- stage: Release
  dependsOn:
  - Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: pipelines/release-pipelines.yml
    parameters:
      imageName: $(imageName)
      azureSubscription: $(azureSubscription)
      functionAppsName: $(functionAppsName)
      functionAppsType: $(functionAppsType)
      environment: $(environment)
      keyVaultEndpoint: $(keyVaultEndpoint)
