apiVersion: v1
kind: Service
metadata:
  name: logging-kibana
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  selector:
    app: logging-kibana