apiVersion: v1
kind: Service
metadata:
  name: demo-svc4
  labels:
    app: demo-service
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: demo-service
#  type: LoadBalancer
#  type: ClusterIP
  type: NodePort