apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-elasticsearch-data
spec:
  capacity:
    storage: {{ .Values.persistence.sizepv }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClass }}
  azureFile:
    secretName: {{ .Values.azureFile.secretName }}
    shareName: {{ .Values.azureFile.shareName }}
    readOnly: {{ .Values.azureFile.readOnly }}
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000