apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-elasticsearch-data
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.sizepvc }}