apiVersion: v1                       
kind: Service                        
metadata:                            
  name: logging-elasticsearch
  labels:                            
    component: logging-elasticsearch
spec:           
  selector:                          
    component: logging-elasticsearch
  ports:                             
  - name: http                       
    port: 9200                       
    protocol: TCP                    
  - name: transport                  
    port: 9300                       
    protocol: TCP
  type: LoadBalancer
  
